version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src
    environment:
      - NODE_ENV=development

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/src
    environment:
      - NODE_ENV=development